/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
exit
/opt/odoo/odoo-10.0/odoo-bin
exit
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
exit
/opt/odoo/odoo-10.0/odoo-bin
exit
/opt/odoo/odoo-10.0/odoo-bin
exit
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
exit
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bine
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
exit
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
exit
/opt/odoo/odoo-10.0/odoo-bin
exit
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
exit
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
cd /opt/odoo/
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
/opt/odoo/odoo-10.0/odoo-bin
